/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
<<<<<<< HEAD
    "aws_appsync_graphqlEndpoint": "https://lxj4zh52lnckfnwykbpltxi7ma.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
=======
>>>>>>> 3041cd5d9a3ef020de1c62f0db6ec6a0cdbce265
    "aws_cognito_identity_pool_id": "us-west-2:b86c0b9e-cd36-4851-9958-b49d28f6330c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Abuw5fyLj",
    "aws_user_pools_web_client_id": "llv44f0g0svn92f7q41ae3qcc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://lxj4zh52lnckfnwykbpltxi7ma.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
